app_name/app_name/absensi/controller.py
# from crypt import methods
# from crypt import methods
from flask import Blueprint, jsonify, request, make_response, render_template,session
from flask.helpers import url_for
from flask_session import Session
from flask import current_app as app
from sklearn.svm import SVR
# from pytest import param
# from regex import D
from flask_jwt_extended import get_jwt, jwt_required
from flask_cors import cross_origin
from werkzeug.utils import redirect, secure_filename
from werkzeug.datastructures import ImmutableMultiDict
from time import gmtime, strftime
import hashlib
import datetime
import requests
import cv2
import matplotlib.pyplot as plt
import os
import numpy as np
import base64
import random
import json
import warnings
import string
import joblib
from .  example import gps_solve
from . models import Data

absensi =  Blueprint('absensi',__name__)
SVR_ant0 = joblib.load('SVR_ant0.sav')
SVR_ant1 =  joblib.load('SVR_ant1.sav')
SVR_ant2 =  joblib.load('SVR_ant2.sav')
SVR_ant3 =  joblib.load('SVR_ant3.sav')
SVR_ant = [SVR_ant0,SVR_ant1,SVR_ant2,SVR_ant3]
Scaler_ant0 =  joblib.load('Scaler_Ant0.sav')
Scaler_ant1 =  joblib.load('Scaler_Ant1.sav')
Scaler_ant2 =  joblib.load('Scaler_ant2.sav')
Scaler_ant3  =  joblib.load('Scaler_Ant3.sav')
Scaler =  [Scaler_ant0,Scaler_ant1,Scaler_ant2,Scaler_ant3]
#region ================================= FUNGSI-FUNGSI AREA ==========================================================================

def tambahLogs(logs):
	f = open(app.config['LOGS'] + "/" + secure_filename(strftime("%Y-%m-%d"))+ ".txt", "a")
	f.write(logs)
	f.close()

def save(encoded_data, filename):
	arr = np.fromstring(base64.b64decode(encoded_data), np.uint8)
	img = cv2.imdecode(arr, cv2.IMREAD_UNCHANGED)
	return cv2.imwrite(filename, img)

def permission_failed():
    return make_response(jsonify({'error': 'Permission Failed','status_code':403}), 403)

def request_failed():
	return make_response(jsonify({'error': 'Request Failed','status_code':403}), 403)

def defined_error(description, error="Defined Error", status_code=499):
	return make_response(jsonify({'description':description,'error': error,'status_code':status_code}), status_code)

def parameter_error(description, error= "Parameter Error", status_code=400):
	if app.config['PRODUCT_ENVIRONMENT'] == "DEV":
		return make_response(jsonify({'description':description,'error': error,'status_code':status_code}), status_code)
	else:
		return make_response(jsonify({'description':"Terjadi Kesalahan Sistem",'error': error,'status_code':status_code}), status_code)

def bad_request(description):
	if app.config['PRODUCT_ENVIRONMENT'] == "DEV":
		return make_response(jsonify({'description':description,'error': 'Bad Request','status_code':400}), 400) #Development
	else:
		return make_response(jsonify({'description':"Terjadi Kesalahan Sistem",'error': 'Bad Request','status_code':400}), 400) #Production

def randomString(stringLength):
	"""Generate a random string of fixed length """
	letters = string.ascii_lowercase
	return ''.join(random.choice(letters) for i in range(stringLength))

def random_string_number_only(stringLength):
	letters = string.digits
	return ''.join(random.choice(letters) for i in range(stringLength))
def rssi_to_range(rssi,svr_model):
    jarak =  svr_model.predict(rssi)
    return jarak
def predict_coordinate(jarak):
    antena0 = [43,45]
    antena1 = [44,-47]
    antena2 = [-46,-48]
    antena3 = [-39,40]
    antena_coordinaate = [antena0,antena1,antena2,antena3]
    coordinate = []
    new_jarak = []
    for i in range(len(jarak)):
        if jarak[i] == 0:
            continue
        else:
            new_jarak.append(jarak[i])
            coordinate.append(antena_coordinaate[i])
    hasil  = gps_solve(new_jarak,coordinate)
    x  = hasil[0]
    y  =  hasil[1]
    return x,y
#endregion ================================= FUNGSI-FUNGSI AREA =============================================================
# region =============================  ABSENSI ===============================================
@absensi.route('archive',methods = ['GET'])
def archive():
    dt = Data()
    kode_mk =  request.args.get('kode_mk')
    pertemuan = request.args.get('pertemuan')
    judul = request.args.get('judul')
    query = "SELECT * FROM absensi LEFT JOIN mahasiswa ON absensi.nim=mahasiswa.nim LEFT JOIN user ON mahasiswa.id_user=user.id_user WHERE `kode mk`=%s AND pertemuan =  %s"
    values =  (kode_mk,3)
    hasil =  dt.get_data(query,values)
    print(hasil)
    return render_template('archive_dosen.html',user=session,judul=judul,pertemuan = pertemuan,kode_mk=kode_mk,scan=hasil)
@absensi.route('/dosen',methods=['GET'])
def dosen():
    dt =  Data()
    kode_mk = request.args.get('kode_mk')
    user =  session
    query =  "SELECT * FROM `pertemuan` LEFT JOIN `mata kuliah` ON `pertemuan`.`kode_mk`=`mata kuliah`.`kode mk` WHERE kode_mk = %s"
    values = (kode_mk,)
    hasil = dt.get_data(query,values)
    query_mk = "SELECT * FROM `mata kuliah` WHERE `kode mk` = %s"
    values_mk =  (kode_mk,)
    mk = dt.get_data(query_mk,values_mk)
    mk = mk[0]
    mk['kode_mk'] = mk['kode mk']
    print(mk)
    last_pertemuan= len(hasil)+1
    print(hasil)
    pertemuan = [
        {
        'pertemuan':1,
        'tanggal':'02/22/2022',
        'status' : '1'
        },
        {
        'pertemuan':2,
        'tanggal':'02/26/2022',
        'status' : '0'
        }
    ]
    return render_template('absensi_dosen.html',user=user,matkul = mk,absensi = hasil,last_pertemuan =last_pertemuan)
@absensi.route('/recap',methods= ['GET'])
def recap():
    dt =  Data()
    kode_mk = request.args.get("kode_mk")
    nim =  request.args.get('nim')
    print('hit api recap kode mk')
    print(kode_mk)
    print(nim)
    query =  "SELECT * FROM `absensi` LEFT JOIN `mata kuliah` ON `absensi`.`kode mk`=`mata kuliah`.`kode mk` WHERE nim=%s AND `absensi`.`kode mk`=%s"
    
    values = (nim,kode_mk,)
    hasil = dt.get_data(query,values)
    print(hasil)
    absensi = [
        {
            'pertemuan':'1',
            'status' : '1',
            'tanggal' : '02/02/2022'
        },
        {
            'pertemuan':'2',
            'status' : '0',
            'tanggal' : '10/02/2022'
        }]
    user = session
    return render_template('absensi_mahasiswa.html',absensi = hasil, user=user,matkul=hasil)
@absensi.route('/create_absensi',methods = ['GET','POST'])
def create_absensi():
    dt =  Data()
    pertemuan = request.form['pertemuan']
    tanggal = request.form['tanggal']
    kode_mk = request.form['kode mk']
    query =  "INSERT INTO pertemuan(pertemuan,kode_mk,tanggal,status) VALUES(%s,%s,%s,%s)"
    values  = (pertemuan,kode_mk,tanggal,0)
    dt.insert_data(query,values)
    query  =  "SELECT * FROM krs WHERE `kode mk` =  %s "
    values =  (kode_mk,)
    hasil = dt.get_data(query,values)
    for mahasiswa in hasil:
        nim =  mahasiswa['nim']
        query =  "SELECT * FROM absensi WHERE `kode mk`=%s AND nim=%s AND pertemuan =%s "
        values =  (kode_mk,nim,pertemuan)
        row = dt.row_count(query,values)
        if row!=0:
            print('tidak diinput')
            continue
        query = "INSERT INTO absensi(`kode mk`,nim,`pertemuan`,status) VALUES(%s,%s,%s,%s)"
        print('berhasil input mahasiswa')
        values =  (kode_mk,nim,pertemuan,0)
        dt.insert_data(query,values)
    return redirect(url_for('absensi.dosen',kode_mk=kode_mk))
@absensi.route('/edit_absensi', methods=['POST'])   
def edit_absensi():
    dt =  Data()
    data =  request.json
    if 'status' not in data:
        return parameter_error('Missing status in request body')
    if 'nim' not in data:
        return parameter_error("Missing nim in Request body")
    if 'kode mk' not in data:
        return parameter_error("Missing kode mk in request body")
    if 'pertemuan' not in data:
        return parameter_error("Missing pertemuan in Request Body")
    status =  data['status']
    kode_mk =  data['kode mk']
    nim =  data['nim']
    pertemuan =  data['pertemuan']
    query = "UPDATE absensi SET status=%s WHERE `kode mk`=%s AND nim=%s AND `pertemuan ke`=%s "
    values =  (status, kode_mk,nim,pertemuan,)
    dt.insert_data(query,values)
    return("Edit Data Berhasil!")


@absensi.route('/get_absensi_dosen')
def get_absensi_dosen():
    hasil =  'data tidak ditemukan'
    dt = Data()
    data =  request.json
    if 'kode mk' not in data:
        return parameter_error("Missing kode mk in request body")
    if 'pertemuan ke' not in data:
        return parameter_error("Missing pertemuan ke in request body")
    kode_mk =  data['kode mk']
    pertemuan =  data['pertemuan']
    query =  "SELECT * FROM absensi WHERE `kode mk` =%s AND `pertemuan ke`=%s"
    values =  (kode_mk,pertemuan)
    dt.get_data(query,values)
    return(jsonify(hasil))

# endregion ========================== ABSENSI ================================================

# region ============================= SCAN ROOM ================================================
@absensi.route('/scan_template',methods=['GET','POST'])
def scan_template():
    dt = Data() 
    kode_mk =  request.args.get('kode_mk')
    pertemuan = request.args.get('pertemuan')
    judul = request.args.get('judul')
    query = "SELECT nama,absensi.status,mahasiswa.nim FROM absensi LEFT JOIN mahasiswa ON absensi.nim=mahasiswa.nim LEFT JOIN user ON mahasiswa.id_user=user.id_user WHERE `kode mk`= %s AND pertemuan =  %s"
    values =  (kode_mk,pertemuan,)
    hasil =  dt.get_data(query,values)
    scan =  [
        {
            'nama' : 'Furqon',
            'nim' : '09011281823054',
            'status' : '1'},
        {
            'nama' : 'Arif',
            'nim' : '09011281823057',
            'status' : '1'
        },
        {
            'nama' : 'Rani',
            'nim' : '09011281823059',
            'status' : 0
        }
        ]
    print(kode_mk)
    print(pertemuan)

app_name/app_name/templates/absensi_dosen.html
{% extends 'sidebar_dosen.html' %}
{% block main_content %}
<div class="container">
    <h1>Rekap Absensi</h1>
    <h4>{% if user %}
            {{user.nama}}
        {% else %}
            Guest
        {% endif %}
    </h4>
    <h4>Mata Kuliah : {% if matkul %}
        {{matkul.judul}}
    {% else %}
        Unknown 
    {% endif %}</h4>
    <table class="table" style="width:60%;">
        <thead>
            <th scope="col">Pertemuan</th>
            <th scope="col">Tanggal</th>
            <th scope="col">Status</th>
            <th scope="col">Detail</th>
        </thead>
        <tbody>
            {% if absensi %}
                {% for absen in absensi %}
                    {% if absen.status==0 %}
                        <tr class="table-danger">
                            <form action="/absensi_dosen">
                            <th scope="row">{{ absen.pertemuan }}</th>
                                <td>{{ absen.tanggal }}</td>
                                <td>Belum dimulai</td>
                                <td><a href="{{url_for('absensi.scan_template',kode_mk=absen.kode_mk,pertemuan=absen.pertemuan,judul=matkul.judul)}}" class="btn btn-primary">Mulai kelas</a></td>
                            </form>
                        </tr>
                    {% else %}
                        <tr class="table-success">
                        <th scope="row">{{ absen.pertemuan }}</th>
                        <td>{{ absen.tanggal }}</td>
                        <td>Telah selesai</td>
                        <td><a href="{{url_for('absensi.archive',kode_mk=absen.kode_mk,pertemuan=absen.pertemuan,judul=matkul.judul)}}" class="btn btn-success">Lihat arsip</a></td>
                        </tr>
                    {% endif %}
                    <!-- <tr>
                    <th scope="row">{{ absen.pertemuan }}</th>
                    <td>{{ absen.tanggal }}</td>
                    <td>{{ absen.status}}</td>
                    </tr> -->
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Buat pertemuan baru
</button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="/absensi/create_absensi" method="POST">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Pertemuan Baru</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <label for="kode mk">Kode MK</label><br>    
                <input type="number"  name="kode mk" value="{{ matkul.kode_mk }}" readonly><br>
                <label for="pertemuan">Pertemuan</label><br>    
                <input type="number"  name="pertemuan" value="{{ last_pertemuan }}" readonly><br>
                <label for="tanggal">Tanggal Pertemuan</label><br>    
                <input type="date" id="tanggal" name="tanggal"></td>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app_name/app_name/templates/absensi_mahasiswa.html
{% extends 'sidebar_mahasiswa.html' %}
{% block main_content %}
<div class="container">
<h1>Rekap Absensi</h1>
<h4>{% if user %}
        {{user.nama}}
    {% else %}
        Guest
    {% endif %}
</h4>
<h4>Mata Kuliah : {% if matkul %}
    {{matkul[0].judul}}
{% else %}
    Unknown 
{% endif %}</h4>

<table class="table" style="width:60%;">
    <thead>
        <th scope="col">Pertemuan</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Keterangan</th>
    </thead>
    <tbody>
        {% if absensi %}
            {% for absen in absensi %}
                {% if absen.status==0 %}
                    <tr class="table-danger">
                    <th scope="row">{{ absen.pertemuan }}</th>
                    <td>{{ absen.tanggal }}</td>
                    <td>Alfa</td>
                    </tr>
                {% else %}
                    <tr class="table-success">
                    <th scope="row">{{ absen.pertemuan }}</th>
                    <td>{{ absen.tanggal }}</td>
                    <td>Hadir</td>
                    </tr>
                {% endif %}
                <!-- <tr>
                <th scope="row">{{ absen.pertemuan }}</th>
                <td>{{ absen.tanggal }}</td>
                <td>{{ absen.status}}</td>
                </tr> -->
            {% endfor %}
        {% endif %}
    </tbody>
</table>
</div>
{% endblock %}

app_name/app_name/templates/archive_dosen.html
{% extends 'sidebar_dosen.html' %}
{% block main_content %}
<div class="container">
    <h1>Absensi Pertemuan {{pertemuan}}</h1>
    <h4>{% if user %}
            {{user.nama}}
        {% else %}
            Guest
        {% endif %}
    </h4>
    <h4>Mata Kuliah : {% if judul %}
        {{judul}}
    {% else %}
        Unknown 
    {% endif %}</h4>
    <div class="row">
        <table class="table" style="width:60%;">
            <thead>
                <th scope="col">Nama</th>
                <th scope="col">NIM</th>
                <th scope="col">Status</th>
                <th scope="col">Detail</th>
            </thead>
            <tbody>
                {% if scan %}
                    {% for mahasiswa in scan %}
                        {% if mahasiswa.status==0 %}
                            <tr class="table-danger">
                                <form action="/absensi_dosen">
                                <th scope="row">{{ mahasiswa.nama }}</th>
                                    <td>{{ mahasiswa.nim }}</td>
                                    <td>Tidak Hadir</td>
                                    <td><a href="" class="btn btn-primary">Edit</a></td>
                                </form>
                            </tr>
                        {% else %}
                            <tr class="table-success">
                            <th scope="row">{{ mahasiswa.nama }}</th>
                            <td>{{ mahasiswa.nim }}</td>
                            <td>Hadir</td>
                            <td><a href="" class="btn btn-primary">Edit</a></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

app_name/app_name/templates/dashboard_dosen.html
{% extends 'sidebar_dosen.html' %}
{% block main_content %}
<div class="container">
    {% if matkul %}
    <div class="row"><h3>Kelas Saya</h3></div>
    <div class="row">
                {% for mk in matkul %}
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{url_for('static',filename='assets/card.jpg')}}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ mk.judul }}</h5>
                            <p class="card-text">
                                {{ mk.deskripsi }}
                            </p>
                            <a href="{{url_for('absensi.dosen',judul=mk.judul,kode_mk=mk['kode mk']|string(),nim=user.nim|string())}}" class="btn btn-primary">Lihat Arsip</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
    {% endif %}
{% endblock %}

app_name/app_name/templates/dashboard_mahasiswa.html
{% extends 'sidebar_mahasiswa.html' %}
{% block main_content %}
<div class="container">
    {% if matkul %}
    <div class="row"><h3>Kelas Saya</h3></div>
    <div class="row">
                {% for mk in matkul %}
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{url_for('static',filename='assets/card.jpg')}}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ mk.judul }}</h5>
                            <p class="card-text">
                                {{ mk.deskripsi }}
                            </p>
                            <a href="{{url_for('absensi.recap',judul=mk.judul,kode_mk=mk['kode mk']|string(),nim=user.nim|string())}}" class="btn btn-primary">Lihat Arsip</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
    {% endif %}
{% endblock %}

app_name/app_name/templates/login_template.html
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{url_for('static',filename='css/login.css')}}">

</head>
<body>
<div class="container-fluid ps-md-0">
    <div class="row g-0">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
        <div class="login d-flex align-items-center py-5">
        <div class="container">
            <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
                <h3 class="login-heading mb-3">SIRAFID</h3>
                <h3 class="login-heading mb-3">Sistem Informasi Absensi berbasis RFID</h3>
                <h3></h3>

                <!-- Sign In Form -->
                <form action="/login_user" methods="POST">
                <div class="form-floating mb-3">
                    <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Email address</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" name="pass" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Password</label>
                </div>

                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                    <label class="form-check-label" for="rememberPasswordCheck">
                    Remember password
                    </label>
                </div>

                <div class="d-grid">
                    <!-- <button class="btn  btn-primary btn-login text-uppercase fw-bold mb-2" id="login" type=""submit>Sign in</button> -->
                    <button class="btn  btn-primary btn-login text-uppercase fw-bold mb-2" type="submit">Sign in</button>
                    <div class="text-center">
                    <a class="small" href="">Forgot password?</a>
                    </div>
                </div>
                </form>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</div>
<script src="js/login.js"></script>
</body>

app_name/app_name/templates/reset_password.html
<body bgcolor="#ffffff" style="margin: 0; padding: 0">
	<center>
		<div style="width: 50%; padding: 10px; background-color: #E7E7E7">
			<div style=" text-align: justify; padding: 50px 0">
				<center>
					<b>
					<font style="font-family: arial; font-size: 25px; color: #353535">RESET PASSWORD BISA NETWORK</font>
					</b>
				</center>
				<br><br>
				<br><br>
				<font style="font-family: arial; color: #353535">
					Hai {{nama}}
					<br>
					<br>
					Kami menerima permintaan untuk memulihkan password. <br><br>
					Password sementara anda <b>{{password}}</b> <br><br>
					Silahkan gunakan password sementara untuk masuk ke akun BISA Network
				</font>
			</div>

			<div style=" text-align: justify; background-color: #fff; padding: 10px">
				<font style="font-family: arial; font-size: 16px; color: #FF1818">
					Email ini dikirim otomatis !
				</font>
				<br>
				<br>
				<font style="font-family: arial; font-size: 12px; color: #888888">
					Mohon jangan membalas email ini.
				</font>
			</div>
		</div>
	</center>
</body>

app_name/app_name/templates/scan_room.html
{% extends 'sidebar_dosen.html' %}
{% block main_content %}
<div class="container">
    <h1>Absensi Pertemuan {{pertemuan}}</h1>
    <h4>{% if user %}
            {{user.nama}}
        {% else %}
            Guest
        {% endif %}
    </h4>
    <h4>Mata Kuliah : {% if judul %}
        {{judul}}
    {% else %}
        Unknown 
    {% endif %}</h4>
    <a href=""class='btn btn-primary'>Scan Room</a>
    <a href="{{url_for('absensi.end_session',kode_mk= kode_mk, pertemuan= pertemuan )}}" class="btn btn-danger">Akhir Kelas</a>
    <div class="row">
        <!-- <img src="{{url_for('static', filename= gambar     )}}" alt="" style="width:400px;height:300px;"> -->
    </div>
    <div class="row">
        <table class="table" id="tabel_absensi" style="width:60%;">
            <thead>
                <th scope="col">Nama</th>
                <th scope="col">NIM</th>
                <th scope="col">Status</th>
                <th scope="col">Detail</th>
            </thead>
            <tbody>
                {% if scan %}
                    {% for mahasiswa in scan %}
                        {% if mahasiswa.status==0 %}
                            <tr class="table-danger">
                                <th scope="row">{{ mahasiswa.nama }}</th>
                                    <td>{{ mahasiswa.nim }}</td>
                                    <td>Tidak Hadir</td>
                                    <td><button nim={{ mahasiswa.nim }} class="btn btn-primary edit">Edit</button></td>
                            </tr>
                        {% else %}
                            <tr class="table-success">
                            <th scope="row">{{ mahasiswa.nama }}</th>
                            <td>{{ mahasiswa.nim }}</td>
                            <td>Hadir</td>
                            <td><button nim= {{ mahasiswa.nim }} class="btn btn-primary edit">Edit</but></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
        <script>
            $('#tabel_absensi').on("click",".edit",function(){
                event.preventDefault();
                const nim = $(this).attr("nim")
                console.log(nim)
                $.ajax({
                    method:"POST",
                    url:"/user/get_mahasiswa",
                    data:JSON.stringify({
                        nim : nim
                    })
                }).done(function(msg){
                    console.log(msg.nama)
                    $("#nama_mhs").val(msg.nama)
                    $("#nim").val(msg.nim)
                    $("#exampleModal").modal("show")
                })
        
            })
        </script>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <form action="/absensi/create_absensi" method="POST">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Kehadiran</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <label for="kode mk">Nama</label><br>
                    <input type="text"  name="kode mk" value="namaaaaa" id="nama_mhs" readonly><br>
                    <label for="pertemuan">NIM</label><br>    
                    <input type="number"  name="pertemuan" value="NIM" id="nim" readonly><br>
                    <label for="Status">Ubah Status menjadi:</label><br>
                    <select class="form-select" aria-label="Default select example">
                        <option selected>Status Kehadiran</option>
                        <option value="1">Hadir</option>
                        <option value="2">Tidak Hadir</option>
                        <option value="3">Izin</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>


{% endblock %}

app_name/app_name/templates/sidebar_dosen.html
<html>
    <head>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{{url_for('static',filename='css/dashboard.css')}}">
        <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    </head>

    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">
                    {% if user %}
                            {{user.nama}}
                            <br>
                            {{user.nip}}
                        {% else %}
                            Guest
                        {% endif %}
                </div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{{url_for('index')}}">Dashboard</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Arsip</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Akun Saya</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{{url_for('logout')}}">Keluar</a>
                </div>
            </div>
            {% block main_content %}{% endblock %}
            <!-- Page content wrapper-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Core theme JS-->
            <script src="{{url_for('static',filename='js/dashboard.js')}}"></script>
    </body>
</html>